name: 'go-sync'
description: 'Github Action for Sync Code to CDN'
author: 'xiexianbin <me@xiexianbin>'
inputs:
  provider:
    description: 'cdn type'
    default: 'aliyun'
    required: true
  access-key:
    description: 'CDN Access Key ID'
    required: true
  access-secret:
    description: 'CDN Access Key Secret'
    required: true
  bucket:
    description: 'CDN Bucket Name'
    required: true
  endpoint:
    description: 'CDN Bucket Endpoint (default "oss-cn-shanghai.aliyuncs.com")'
    required: true
  cache:
    description: 'the cache file path (default "/tmp/<bucketName>.json")'
    required: false
  exclude:
    description: 'exclude file or dir, comma-separated string'
    required: false
  source:
    description: 'the source dir public to cdn'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: 'blue'
  icon: 'link-2'
